global:
  smtp_smarthost: "some.smtp.com: 25"
  smtp_from: "some@email.com"
  smtp_auth_username: "SomeUser"
  smtp_auth_password: "SomePass"
  smtp_require_tls: false

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10m
  receiver: live-monitoring

receivers:
  - name: "live-monitoring"
    email_configs:
      - to: "YourEmailForAlerts@email.com"
