global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["<host.name>:9093"]

rule_files:
  - "node_down.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["<host.name>:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["<host.name>:8080"]

  - job_name: "node"
    scrape_interval: 8s
    static_configs:
      - targets: ["<host.name>:9100"]
